// frontend/src/components/layout/Navbar.vue
<script setup lang="ts">
import { useRouter, RouterLink } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import api from '@/lib/axios'
import Cookies from 'js-cookie'

const router = useRouter()
const auth = useAuthStore()

async function logout() {
  try {
    await api.post('/api/auth/logout/')
  } catch {
    // ignore errors — always clear local auth
  } finally {
    auth.clearAuth()
    Cookies.remove('access_token')
    router.push('/login')
  }
}
</script>

<template>
  <header class="bg-ibook-brown-800 text-white shadow-md">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
      <div class="flex items-center justify-between h-16">
        <!-- Logo -->
        <RouterLink
          to="/customer/explore"
          class="text-2xl font-black tracking-tight text-ibook-gold-400 hover:text-ibook-gold-500 transition-colors"
        >
          IBook
        </RouterLink>

        <!-- Nav links -->
        <nav class="flex items-center gap-6">
          <RouterLink
            to="/customer/explore"
            class="text-ibook-brown-200 hover:text-white transition-colors text-sm font-medium"
            active-class="text-white"
          >
            Explore
          </RouterLink>
          <RouterLink
            to="/customer/appointments"
            class="text-ibook-brown-200 hover:text-white transition-colors text-sm font-medium"
            active-class="text-white"
          >
            Appointments
          </RouterLink>
          <RouterLink
            to="/customer/settings"
            class="text-ibook-brown-200 hover:text-white transition-colors text-sm font-medium"
            active-class="text-white"
          >
            Settings
          </RouterLink>
        </nav>

        <!-- User area -->
        <div class="flex items-center gap-4">
          <span class="text-ibook-brown-300 text-sm hidden sm:block">
            {{ auth.user?.fullName }}
          </span>
          <button
            @click="logout"
            class="bg-ibook-brown-600 hover:bg-ibook-brown-500 text-white text-sm font-medium px-4 py-2 rounded-lg transition-colors cursor-pointer"
          >
            Logout
          </button>
        </div>
      </div>
    </div>
  </header>
</template>

// frontend/src/components/layout/Navbar.tsx
'use client'

import Link from 'next/link'
import { useRouter } from 'next/navigation'
import Cookies from 'js-cookie'
import { api } from '@/lib/axios'
import { useAuth } from '@/hooks/useAuth'
import { HydrationGuard } from '@/components/HydrationGuard'

function NavbarContent() {
  const router = useRouter()
  const { user, clearAuth } = useAuth()

  const handleLogout = async () => {
    try {
      await api.post('/api/auth/logout/')
    } catch {
      // Continue with logout even if API call fails
    }
    clearAuth()
    Cookies.remove('access_token')
    router.push('/login')
  }

  return (
    <header className="sticky top-0 z-40 w-full border-b border-ibook-brown-100 bg-ibook-cream">
      <div className="mx-auto flex h-14 max-w-screen-xl items-center justify-between px-4 sm:px-6">
        {/* Logo */}
        <Link href="/customer/explore" className="text-xl font-bold text-ibook-brown-900">
          IBook
        </Link>

        {/* Nav links */}
        <nav className="hidden sm:flex items-center gap-6 text-sm font-medium text-ibook-brown-700">
          <Link href="/customer/explore" className="hover:text-ibook-brown-900 transition-colors">
            Explore
          </Link>
          <Link href="/customer/appointments" className="hover:text-ibook-brown-900 transition-colors">
            Appointments
          </Link>
        </nav>

        {/* User actions */}
        <div className="flex items-center gap-3">
          {user && (
            <span className="hidden sm:block text-sm text-ibook-brown-500">
              {user.fullName}
            </span>
          )}
          <Link
            href="/settings"
            className="text-sm text-ibook-brown-700 hover:text-ibook-brown-900 transition-colors"
          >
            Settings
          </Link>
          <button
            onClick={handleLogout}
            className="text-sm font-medium text-ibook-brown-700 hover:text-ibook-brown-900 transition-colors border border-ibook-brown-200 rounded-lg px-3 py-1.5 hover:bg-ibook-brown-100"
          >
            Logout
          </button>
        </div>
      </div>
    </header>
  )
}

export function Navbar() {
  return (
    <HydrationGuard>
      <NavbarContent />
    </HydrationGuard>
  )
}
