// frontend/src/components/layout/Sidebar.tsx
'use client'

import Link from 'next/link'
import { usePathname, useRouter } from 'next/navigation'
import Cookies from 'js-cookie'
import { api } from '@/lib/axios'
import { useAuth } from '@/hooks/useAuth'
import { HydrationGuard } from '@/components/HydrationGuard'
import { cn } from '@/lib/utils'

interface NavItem {
  href: string
  label: string
}

interface SidebarContentProps {
  navItems: NavItem[]
}

function SidebarContent({ navItems }: SidebarContentProps) {
  const router = useRouter()
  const pathname = usePathname()
  const { clearAuth } = useAuth()

  const handleLogout = async () => {
    try {
      await api.post('/api/auth/logout/')
    } catch {
      // Continue with logout even if API call fails
    }
    clearAuth()
    Cookies.remove('access_token')
    router.push('/login')
  }

  return (
    <aside className="flex h-screen w-60 flex-col border-r border-ibook-brown-100 bg-ibook-cream">
      {/* Logo */}
      <div className="flex h-14 items-center border-b border-ibook-brown-100 px-5">
        <span className="text-xl font-bold text-ibook-brown-900">IBook</span>
      </div>

      {/* Navigation */}
      <nav className="flex-1 space-y-1 px-3 py-4">
        {navItems.map((item) => (
          <Link
            key={item.href}
            href={item.href}
            className={cn(
              'flex items-center rounded-lg px-3 py-2 text-sm font-medium transition-colors',
              pathname === item.href || pathname.startsWith(item.href + '/')
                ? 'bg-ibook-brown-700 text-white'
                : 'text-ibook-brown-700 hover:bg-ibook-brown-100 hover:text-ibook-brown-900'
            )}
          >
            {item.label}
          </Link>
        ))}
      </nav>

      {/* Logout */}
      <div className="border-t border-ibook-brown-100 px-3 py-4">
        <button
          onClick={handleLogout}
          className="flex w-full items-center rounded-lg px-3 py-2 text-sm font-medium text-ibook-brown-700 hover:bg-ibook-brown-100 hover:text-ibook-brown-900 transition-colors"
        >
          Logout
        </button>
      </div>
    </aside>
  )
}

interface SidebarProps {
  navItems: NavItem[]
}

export function Sidebar({ navItems }: SidebarProps) {
  return (
    <HydrationGuard>
      <SidebarContent navItems={navItems} />
    </HydrationGuard>
  )
}

// frontend/src/components/layout/Sidebar.vue
<script setup lang="ts">
import { useRouter, RouterLink } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import api from '@/lib/axios'
import Cookies from 'js-cookie'

defineProps<{
  navItems: Array<{ label: string; to: string }>
}>()

const router = useRouter()
const auth = useAuthStore()

async function logout() {
  try {
    await api.post('/api/auth/logout/')
  } catch {
    // ignore errors — always clear local auth
  } finally {
    auth.clearAuth()
    Cookies.remove('access_token')
    router.push('/login')
  }
}
</script>

<template>
  <aside class="w-64 min-h-screen bg-ibook-brown-900 text-white flex flex-col shadow-xl">
    <!-- Logo -->
    <div class="px-6 py-6 border-b border-ibook-brown-700">
      <span class="text-2xl font-black tracking-tight text-ibook-gold-400">IBook</span>
      <p class="text-ibook-brown-400 text-xs mt-1">{{ auth.user?.fullName }}</p>
    </div>

    <!-- Navigation -->
    <nav class="flex-1 px-4 py-6 space-y-1">
      <RouterLink
        v-for="item in navItems"
        :key="item.to"
        :to="item.to"
        class="flex items-center gap-3 px-4 py-3 rounded-lg text-ibook-brown-300 hover:bg-ibook-brown-700 hover:text-white transition-colors text-sm font-medium"
        active-class="bg-ibook-brown-700 text-white"
      >
        {{ item.label }}
      </RouterLink>
    </nav>

    <!-- Logout -->
    <div class="px-4 py-6 border-t border-ibook-brown-700">
      <button
        @click="logout"
        class="w-full flex items-center gap-3 px-4 py-3 rounded-lg text-ibook-brown-400 hover:bg-ibook-brown-700 hover:text-white transition-colors text-sm font-medium cursor-pointer"
      >
        <svg
          xmlns="http://www.w3.org/2000/svg"
          class="h-4 w-4"
          fill="none"
          viewBox="0 0 24 24"
          stroke="currentColor"
          stroke-width="2"
        >
          <path
            stroke-linecap="round"
            stroke-linejoin="round"
            d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1"
          />
        </svg>
        Logout
      </button>
    </div>
  </aside>
</template>
