// frontend/src/components/settings/SettingsContent.vue
<script setup lang="ts">
import { ref, reactive, watch } from 'vue'
import { useQuery, useMutation, useQueryClient } from '@tanstack/vue-query'
import { useToast } from 'vue-toastification'
import api from '@/lib/axios'
import { useAuthStore } from '@/stores/auth'
import SkeletonBlock from '@/components/ui/SkeletonBlock.vue'

const toast = useToast()

interface ProfileData {
  id: number
  email: string
  full_name: string
  phone_number?: string
  avatar?: string
  role: string
  bio?: string
  years_of_experience?: number
}

const auth = useAuthStore()
const queryClient = useQueryClient()

const { data: profile, isLoading, isError } = useQuery<ProfileData>({
  queryKey: ['profile'],
  queryFn: async () => {
    const res = await api.get<ProfileData>('/api/auth/profile/')
    return res.data
  },
})

const form = reactive({
  fullName: '',
  phone: '',
  avatarUrl: '',
  bio: '',
  yearsOfExperience: '' as string | number,
})

const successMsg = ref('')
const errorMsg = ref('')

// Populate form when profile loads
watch(profile, (p) => {
  if (p) {
    form.fullName = p.full_name ?? ''
    form.phone = p.phone_number ?? ''
    form.avatarUrl = p.avatar ?? ''
    form.bio = p.bio ?? ''
    form.yearsOfExperience = p.years_of_experience ?? ''
  }
})

const { mutate: saveProfile, isPending: isSaving } = useMutation({
  mutationFn: async () => {
    const nameParts = form.fullName.trim().split(' ', 2)
    const payload: Record<string, unknown> = {
      first_name: nameParts[0] || '',
      last_name: nameParts[1] || '',
    }
    if (form.phone !== undefined) payload.phone_number = form.phone || null
    if (form.avatarUrl !== undefined) payload.avatar = form.avatarUrl || null

    const isBarber = auth.user?.role === 'BARBER'
    if (isBarber) {
      payload.bio = form.bio || null
      payload.years_of_experience = form.yearsOfExperience !== '' ? Number(form.yearsOfExperience) : null
    }

    const res = await api.patch<ProfileData>('/api/auth/profile/', payload)
    return res.data
  },
  onSuccess: (data) => {
    queryClient.setQueryData(['profile'], data)
    // Update auth store with new name
    if (auth.user) {
      auth.setAuth({
        user: { ...auth.user, fullName: data.full_name },
        accessToken: auth.accessToken ?? '',
      })
    }
    successMsg.value = 'Profile updated successfully.'
    errorMsg.value = ''
    toast.success('Profile updated')
    setTimeout(() => { successMsg.value = '' }, 4000)
  },
  onError: () => {
    errorMsg.value = 'Failed to update profile. Please try again.'
    successMsg.value = ''
    toast.error('Failed to update profile. Please try again.')
  },
})

function roleBadgeClass(role: string) {
  switch (role) {
    case 'CUSTOMER':
      return 'bg-ibook-brown-100 text-ibook-brown-700'
    case 'BARBER':
      return 'bg-ibook-gold-400 text-white'
    case 'SHOP_OWNER':
      return 'bg-ibook-brown-800 text-white'
    default:
      return 'bg-gray-100 text-gray-600'
  }
}

function roleLabel(role: string) {
  switch (role) {
    case 'CUSTOMER':
      return 'Customer'
    case 'BARBER':
      return 'Barber'
    case 'SHOP_OWNER':
      return 'Shop Owner'
    default:
      return role
  }
}

function submit() {
  saveProfile()
}
</script>

<template>
  <div class="p-4 md:p-8 max-w-2xl">
    <!-- Header -->
    <div class="mb-6 md:mb-8">
      <h1 class="text-xl md:text-3xl font-bold text-ibook-brown-900">Settings</h1>
      <p class="mt-1 text-ibook-brown-500">Manage your account information.</p>
    </div>

    <!-- Loading skeleton -->
    <div v-if="isLoading" class="space-y-4">
      <SkeletonBlock height="2.5rem" />
      <SkeletonBlock height="2.5rem" />
      <SkeletonBlock height="2.5rem" />
    </div>

    <!-- Error loading -->
    <div
      v-else-if="isError"
      class="px-4 py-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700"
    >
      Failed to load profile. Please refresh the page.
    </div>

    <!-- Form -->
    <form v-else @submit.prevent="submit" novalidate>
      <!-- Role badge -->
      <div class="mb-6 flex items-center gap-3">
        <span
          class="inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold tracking-wide"
          :class="roleBadgeClass(profile?.role ?? '')"
        >
          {{ roleLabel(profile?.role ?? '') }}
        </span>
      </div>

      <!-- Full Name -->
      <div class="mb-5">
        <label for="fullName" class="block text-sm font-semibold text-ibook-brown-700 mb-1.5">
          Full Name
        </label>
        <input
          id="fullName"
          v-model="form.fullName"
          type="text"
          autocomplete="name"
          class="w-full px-4 py-3 rounded-lg border border-ibook-brown-200 text-ibook-brown-900 bg-white focus:outline-none focus:ring-2 focus:ring-ibook-brown-400 focus:border-ibook-brown-400 transition-colors"
        />
      </div>

      <!-- Email (readonly) -->
      <div class="mb-5">
        <label for="email" class="block text-sm font-semibold text-ibook-brown-700 mb-1.5">
          Email
          <span class="font-normal text-ibook-brown-400">(cannot be changed)</span>
        </label>
        <input
          id="email"
          :value="profile?.email ?? ''"
          type="email"
          readonly
          class="w-full px-4 py-3 rounded-lg border border-ibook-brown-100 text-ibook-brown-500 bg-ibook-brown-50 cursor-not-allowed"
        />
      </div>

      <!-- Phone (optional) -->
      <div class="mb-5">
        <label for="phone" class="block text-sm font-semibold text-ibook-brown-700 mb-1.5">
          Phone
          <span class="font-normal text-ibook-brown-400">(optional)</span>
        </label>
        <input
          id="phone"
          v-model="form.phone"
          type="tel"
          autocomplete="tel"
          placeholder="+1 555 000 0000"
          class="w-full px-4 py-3 rounded-lg border border-ibook-brown-200 text-ibook-brown-900 bg-white focus:outline-none focus:ring-2 focus:ring-ibook-brown-400 focus:border-ibook-brown-400 transition-colors"
        />
      </div>

      <!-- Avatar URL (optional) -->
      <div class="mb-5">
        <label for="avatarUrl" class="block text-sm font-semibold text-ibook-brown-700 mb-1.5">
          Avatar URL
          <span class="font-normal text-ibook-brown-400">(optional)</span>
        </label>
        <input
          id="avatarUrl"
          v-model="form.avatarUrl"
          type="url"
          placeholder="https://example.com/avatar.jpg"
          class="w-full px-4 py-3 rounded-lg border border-ibook-brown-200 text-ibook-brown-900 bg-white focus:outline-none focus:ring-2 focus:ring-ibook-brown-400 focus:border-ibook-brown-400 transition-colors"
        />
      </div>

      <!-- Barber-only fields -->
      <template v-if="auth.user?.role === 'BARBER'">
        <div class="mb-5">
          <label for="bio" class="block text-sm font-semibold text-ibook-brown-700 mb-1.5">
            Bio
            <span class="font-normal text-ibook-brown-400">(optional)</span>
          </label>
          <textarea
            id="bio"
            v-model="form.bio"
            rows="4"
            placeholder="Tell clients about yourself and your specialties…"
            class="w-full px-4 py-3 rounded-lg border border-ibook-brown-200 text-ibook-brown-900 bg-white focus:outline-none focus:ring-2 focus:ring-ibook-brown-400 focus:border-ibook-brown-400 transition-colors resize-none"
          ></textarea>
        </div>

        <div class="mb-6">
          <label for="experience" class="block text-sm font-semibold text-ibook-brown-700 mb-1.5">
            Years of Experience
            <span class="font-normal text-ibook-brown-400">(optional)</span>
          </label>
          <input
            id="experience"
            v-model="form.yearsOfExperience"
            type="number"
            min="0"
            max="60"
            placeholder="0"
            class="w-full px-4 py-3 rounded-lg border border-ibook-brown-200 text-ibook-brown-900 bg-white focus:outline-none focus:ring-2 focus:ring-ibook-brown-400 focus:border-ibook-brown-400 transition-colors"
          />
        </div>
      </template>

      <!-- Success message -->
      <div
        v-if="successMsg"
        class="mb-5 px-4 py-3 bg-green-50 border border-green-200 rounded-lg text-sm text-green-700"
      >
        {{ successMsg }}
      </div>

      <!-- Error message -->
      <div
        v-if="errorMsg"
        class="mb-5 px-4 py-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700"
      >
        {{ errorMsg }}
      </div>

      <!-- Save button -->
      <button
        type="submit"
        :disabled="isSaving"
        class="py-3 px-8 bg-ibook-brown-700 hover:bg-ibook-brown-600 text-white font-semibold rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-ibook-brown-400 focus:ring-offset-2 disabled:opacity-60 disabled:cursor-not-allowed cursor-pointer"
      >
        <span v-if="isSaving">Saving…</span>
        <span v-else>Save Changes</span>
      </button>
    </form>
  </div>
</template>

// frontend/src/components/settings/SettingsContent.tsx
'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { api } from '@/lib/axios'
import { useAuth } from '@/hooks/useAuth'
import {
  Form,
  FormField,
  FormItem,
  FormLabel,
  FormControl,
  FormMessage,
} from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'

interface Profile {
  id: number
  email: string
  role: 'CUSTOMER' | 'BARBER' | 'SHOP_OWNER'
  full_name: string
  phone_number: string | null
  avatar: string | null
  bio: string | null
  years_of_experience: number | string | null
}

const settingsSchema = z.object({
  full_name: z.string().min(1, 'Full name is required'),
  phone_number: z.string().optional(),
  avatar: z.string().optional(),
  bio: z.string().optional(),
  years_of_experience: z.string().optional(),
})

type SettingsFormValues = z.infer<typeof settingsSchema>

const ROLE_LABELS: Record<string, string> = {
  CUSTOMER: 'Customer',
  BARBER: 'Barber',
  SHOP_OWNER: 'Shop Owner',
}

export function SettingsContent() {
  const router = useRouter()
  const { isAuthenticated, user } = useAuth()
  const queryClient = useQueryClient()
  const [saveMessage, setSaveMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null)

  useEffect(() => {
    if (!isAuthenticated) {
      router.replace('/login?returnUrl=/settings')
    }
  }, [isAuthenticated, router])

  const { data: profile, isLoading } = useQuery<Profile>({
    queryKey: ['profile'],
    queryFn: () => api.get('/api/auth/profile/').then((r) => r.data),
    enabled: isAuthenticated,
  })

  const form = useForm<SettingsFormValues>({
    resolver: zodResolver(settingsSchema),
    defaultValues: {
      full_name: '',
      phone_number: '',
      avatar: '',
      bio: '',
      years_of_experience: '',
    },
  })

  useEffect(() => {
    if (profile) {
      form.reset({
        full_name: profile.full_name || '',
        phone_number: profile.phone_number || '',
        avatar: profile.avatar || '',
        bio: profile.bio || '',
        years_of_experience:
        profile.years_of_experience != null ? String(profile.years_of_experience) : '',
      })
    }
  }, [profile, form])

  const mutation = useMutation({
    mutationFn: (data: Partial<SettingsFormValues>) => api.patch('/api/auth/profile/', data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ['profile'] })
      setSaveMessage({ type: 'success', text: 'Profile updated successfully.' })
      setTimeout(() => setSaveMessage(null), 3000)
    },
    onError: () => {
      setSaveMessage({ type: 'error', text: 'Failed to save changes. Please try again.' })
    },
  })

  const onSubmit = (values: SettingsFormValues) => {
    setSaveMessage(null)
    const payload: Partial<SettingsFormValues> = { full_name: values.full_name }
    if (values.phone_number !== undefined) payload.phone_number = values.phone_number
    if (values.avatar !== undefined) payload.avatar = values.avatar
    if (user?.role === 'BARBER') {
      if (values.bio !== undefined) payload.bio = values.bio
      if (values.years_of_experience !== undefined)
        payload.years_of_experience = values.years_of_experience
    }
    mutation.mutate(payload)
  }

  if (!isAuthenticated) return null

  if (isLoading) {
    return (
      <div className="flex items-center justify-center py-20">
        <p className="text-ibook-brown-500">Loading profile...</p>
      </div>
    )
  }

  return (
    <div className="w-full">
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-ibook-brown-900">Settings</h1>
        <p className="mt-1 text-ibook-brown-500">Manage your profile information</p>
      </div>

      {profile && (
        <div className="mb-6">
          <span className="inline-block rounded-full bg-ibook-brown-100 px-3 py-1 text-xs font-semibold uppercase tracking-wide text-ibook-brown-700">
            {ROLE_LABELS[profile.role] ?? profile.role}
          </span>
        </div>
      )}

      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-5 max-w-2xl">
          <FormField
            control={form.control}
            name="full_name"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="text-ibook-brown-700 font-medium">Full Name</FormLabel>
                <FormControl>
                  <Input
                    placeholder="Your full name"
                    className="bg-white border-ibook-brown-100"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <div className="space-y-2">
            <label className="block text-sm font-medium text-ibook-brown-700">Email</label>
            <Input
              value={profile?.email ?? ''}
              readOnly
              className="bg-ibook-brown-50 border-ibook-brown-100 text-ibook-brown-500 cursor-not-allowed"
            />
          </div>

          <FormField
            control={form.control}
            name="phone_number"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="text-ibook-brown-700 font-medium">
                  Phone Number{' '}
                  <span className="font-normal text-ibook-brown-500">(optional)</span>
                </FormLabel>
                <FormControl>
                  <Input
                    type="tel"
                    placeholder="+1 555 000 0000"
                    className="bg-white border-ibook-brown-100"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="avatar"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="text-ibook-brown-700 font-medium">
                  Avatar URL{' '}
                  <span className="font-normal text-ibook-brown-500">(optional)</span>
                </FormLabel>
                <FormControl>
                  <Input
                    type="url"
                    placeholder="https://example.com/avatar.jpg"
                    className="bg-white border-ibook-brown-100"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          {user?.role === 'BARBER' && (
            <>
              <FormField
                control={form.control}
                name="bio"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="text-ibook-brown-700 font-medium">Bio</FormLabel>
                    <FormControl>
                      <textarea
                        rows={3}
                        placeholder="Tell customers about yourself..."
                        className="w-full rounded-lg border border-ibook-brown-100 bg-white px-3 py-2 text-sm text-ibook-brown-900 placeholder:text-ibook-brown-400 focus:outline-none focus:border-ibook-gold-400"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <FormField
                control={form.control}
                name="years_of_experience"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel className="text-ibook-brown-700 font-medium">
                      Years of Experience
                    </FormLabel>
                    <FormControl>
                      <Input
                        type="number"
                        min={0}
                        placeholder="5"
                        className="bg-white border-ibook-brown-100"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </>
          )}

          {saveMessage && (
            <div
              className={`rounded-lg px-4 py-3 text-sm ${
                saveMessage.type === 'success'
                  ? 'bg-green-50 border border-green-200 text-green-700'
                  : 'bg-destructive/10 border border-destructive/50 text-destructive'
              }`}
            >
              {saveMessage.text}
            </div>
          )}

          <Button
            type="submit"
            disabled={mutation.isPending}
            className="w-full bg-ibook-brown-700 hover:bg-ibook-brown-900 text-white font-semibold py-2.5 rounded-xl h-auto"
          >
            {mutation.isPending ? 'Saving...' : 'Save changes'}
          </Button>
        </form>
      </Form>
    </div>
  )
}
