// frontend/src/components/auth/CustomerRegisterForm.tsx
'use client'

import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import Link from 'next/link'
import { api } from '@/lib/axios'
import {
  Form,
  FormField,
  FormItem,
  FormLabel,
  FormControl,
  FormMessage,
} from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'

const customerSchema = z.object({
  full_name: z.string().min(1, 'Full name is required'),
  email: z.string().email('Please enter a valid email address'),
  password: z
    .string()
    .min(8, 'Password must be at least 8 characters')
    .regex(/[A-Za-z]/, 'Password must contain at least one letter')
    .regex(/[0-9]/, 'Password must contain at least one number'),
  phone_number: z.string().optional(),
})

type CustomerFormValues = z.infer<typeof customerSchema>

export function CustomerRegisterForm() {
  const [success, setSuccess] = useState(false)
  const [serverError, setServerError] = useState<string | null>(null)

  const form = useForm<CustomerFormValues>({
    resolver: zodResolver(customerSchema),
    defaultValues: {
      full_name: '',
      email: '',
      password: '',
      phone_number: '',
    },
  })

  const onSubmit = async (values: CustomerFormValues) => {
    setServerError(null)
    try {
      const payload: Record<string, string> = {
        full_name: values.full_name,
        email: values.email,
        password: values.password,
      }
      if (values.phone_number) {
        payload.phone_number = values.phone_number
      }
      await api.post('/api/auth/register/customer/', payload)
      setSuccess(true)
    } catch (err: unknown) {
      const error = err as {
        response?: {
          data?: Record<string, string | string[]>
        }
      }
      const data = error?.response?.data
      if (data) {
        const firstKey = Object.keys(data)[0]
        const msg = Array.isArray(data[firstKey]) ? data[firstKey][0] : data[firstKey]
        setServerError(String(msg))
      } else {
        setServerError('Registration failed. Please try again.')
      }
    }
  }

  if (success) {
    return (
      <div className="space-y-8">
        <div>
          <h2 className="text-3xl font-bold text-ibook-brown-900">Check your email</h2>
          <p className="mt-2 text-ibook-brown-500">
            We sent a verification link to your email address. Please click the link to activate
            your account before logging in.
          </p>
        </div>
        <p className="text-sm text-ibook-brown-500">
          Already verified?{' '}
          <Link href="/login" className="font-medium text-ibook-brown-700 underline underline-offset-4">
            Log in
          </Link>
        </p>
      </div>
    )
  }

  return (
    <div className="space-y-8">
      <div>
        <h2 className="text-3xl font-bold text-ibook-brown-900">Create your account</h2>
        <p className="mt-2 text-ibook-brown-500">Join IBook as a customer</p>
      </div>

      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-5">
          <FormField
            control={form.control}
            name="full_name"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="text-ibook-brown-700 font-medium">Full Name</FormLabel>
                <FormControl>
                  <Input
                    placeholder="Jane Doe"
                    autoComplete="name"
                    className="bg-white border-ibook-brown-100 focus:border-ibook-gold-400"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="email"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="text-ibook-brown-700 font-medium">Email</FormLabel>
                <FormControl>
                  <Input
                    type="email"
                    placeholder="you@example.com"
                    autoComplete="email"
                    className="bg-white border-ibook-brown-100 focus:border-ibook-gold-400"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="text-ibook-brown-700 font-medium">Password</FormLabel>
                <FormControl>
                  <Input
                    type="password"
                    placeholder="Min 8 chars, letter + number"
                    autoComplete="new-password"
                    className="bg-white border-ibook-brown-100 focus:border-ibook-gold-400"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="phone_number"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="text-ibook-brown-700 font-medium">
                  Phone Number{' '}
                  <span className="font-normal text-ibook-brown-500">(optional)</span>
                </FormLabel>
                <FormControl>
                  <Input
                    type="tel"
                    placeholder="+1 555 000 0000"
                    autoComplete="tel"
                    className="bg-white border-ibook-brown-100 focus:border-ibook-gold-400"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          {serverError && (
            <div className="rounded-lg border border-destructive/50 bg-destructive/10 px-4 py-3 text-sm text-destructive">
              {serverError}
            </div>
          )}

          <Button
            type="submit"
            disabled={form.formState.isSubmitting}
            className="w-full bg-ibook-brown-700 hover:bg-ibook-brown-900 text-white font-semibold py-2.5 rounded-xl h-auto"
          >
            {form.formState.isSubmitting ? 'Creating account…' : 'Create account'}
          </Button>
        </form>
      </Form>

      <p className="text-center text-sm text-ibook-brown-500">
        Already have an account?{' '}
        <Link href="/login" className="font-medium text-ibook-brown-700 underline underline-offset-4">
          Log in
        </Link>
      </p>
    </div>
  )
}

// frontend/src/components/auth/CustomerRegisterForm.vue
<script setup lang="ts">
import { ref, reactive } from 'vue'
import api from '@/lib/axios'

const emit = defineEmits<{
  (e: 'success'): void
}>()

const form = reactive({
  fullName: '',
  email: '',
  password: '',
  phone: '',
})

const errors = reactive({
  fullName: '',
  email: '',
  password: '',
  phone: '',
  general: '',
})

const loading = ref(false)

function validateEmail(email: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)
}

function validatePassword(password: string) {
  // 8+ chars with at least one letter and one number
  return password.length >= 8 && /[a-zA-Z]/.test(password) && /[0-9]/.test(password)
}

function validate() {
  errors.fullName = ''
  errors.email = ''
  errors.password = ''
  errors.phone = ''
  errors.general = ''
  let valid = true

  if (!form.fullName.trim()) {
    errors.fullName = 'Full name is required.'
    valid = false
  }

  if (!form.email) {
    errors.email = 'Email is required.'
    valid = false
  } else if (!validateEmail(form.email)) {
    errors.email = 'Please enter a valid email address.'
    valid = false
  }

  if (!form.password) {
    errors.password = 'Password is required.'
    valid = false
  } else if (!validatePassword(form.password)) {
    errors.password = 'Password must be at least 8 characters and include a letter and a number.'
    valid = false
  }

  return valid
}

async function submit() {
  if (!validate()) return
  loading.value = true

  try {
    await api.post('/api/auth/register/customer/', {
      email: form.email,
      password: form.password,
      full_name: form.fullName,
      ...(form.phone ? { phone_number: form.phone } : {}),
    })
    emit('success')
  } catch (err: unknown) {
    const axiosErr = err as {
      response?: {
        data?: Record<string, string | string[]>
      }
    }
    const data = axiosErr.response?.data
    if (data) {
      if (data.email) errors.email = Array.isArray(data.email) ? data.email[0] : data.email
      if (data.password)
        errors.password = Array.isArray(data.password) ? data.password[0] : data.password
      if (data.full_name)
        errors.fullName = Array.isArray(data.full_name) ? data.full_name[0] : data.full_name
      if (data.phone_number)
        errors.phone = Array.isArray(data.phone_number) ? data.phone_number[0] : data.phone_number
      if (data.non_field_errors)
        errors.general = Array.isArray(data.non_field_errors)
          ? data.non_field_errors[0]
          : data.non_field_errors
      if (data.detail)
        errors.general = typeof data.detail === 'string' ? data.detail : (data.detail as string[])[0]
    } else {
      errors.general = 'Something went wrong. Please try again.'
    }
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <form @submit.prevent="submit" novalidate>
    <!-- Full Name -->
    <div class="mb-5">
      <label for="fullName" class="block text-sm font-semibold text-ibook-brown-700 mb-1.5">
        Full Name
      </label>
      <input
        id="fullName"
        v-model="form.fullName"
        type="text"
        autocomplete="name"
        placeholder="John Smith"
        class="w-full px-4 py-3 rounded-lg border text-ibook-brown-900 placeholder-ibook-brown-300 bg-white focus:outline-none focus:ring-2 transition-colors"
        :class="
          errors.fullName
            ? 'border-red-400 focus:ring-red-300'
            : 'border-ibook-brown-200 focus:ring-ibook-brown-400 focus:border-ibook-brown-400'
        "
      />
      <p v-if="errors.fullName" class="mt-1.5 text-sm text-red-600">{{ errors.fullName }}</p>
    </div>

    <!-- Email -->
    <div class="mb-5">
      <label for="email" class="block text-sm font-semibold text-ibook-brown-700 mb-1.5">
        Email
      </label>
      <input
        id="email"
        v-model="form.email"
        type="email"
        autocomplete="email"
        placeholder="you@example.com"
        class="w-full px-4 py-3 rounded-lg border text-ibook-brown-900 placeholder-ibook-brown-300 bg-white focus:outline-none focus:ring-2 transition-colors"
        :class="
          errors.email
            ? 'border-red-400 focus:ring-red-300'
            : 'border-ibook-brown-200 focus:ring-ibook-brown-400 focus:border-ibook-brown-400'
        "
      />
      <p v-if="errors.email" class="mt-1.5 text-sm text-red-600">{{ errors.email }}</p>
    </div>

    <!-- Password -->
    <div class="mb-5">
      <label for="password" class="block text-sm font-semibold text-ibook-brown-700 mb-1.5">
        Password
      </label>
      <input
        id="password"
        v-model="form.password"
        type="password"
        autocomplete="new-password"
        placeholder="••••••••"
        class="w-full px-4 py-3 rounded-lg border text-ibook-brown-900 placeholder-ibook-brown-300 bg-white focus:outline-none focus:ring-2 transition-colors"
        :class="
          errors.password
            ? 'border-red-400 focus:ring-red-300'
            : 'border-ibook-brown-200 focus:ring-ibook-brown-400 focus:border-ibook-brown-400'
        "
      />
      <p v-if="errors.password" class="mt-1.5 text-sm text-red-600">{{ errors.password }}</p>
      <p v-else class="mt-1 text-xs text-ibook-brown-400">
        Must be 8+ characters with at least one letter and one number.
      </p>
    </div>

    <!-- Phone (optional) -->
    <div class="mb-6">
      <label for="phone" class="block text-sm font-semibold text-ibook-brown-700 mb-1.5">
        Phone
        <span class="font-normal text-ibook-brown-400">(optional)</span>
      </label>
      <input
        id="phone"
        v-model="form.phone"
        type="tel"
        autocomplete="tel"
        placeholder="+1 555 000 0000"
        class="w-full px-4 py-3 rounded-lg border border-ibook-brown-200 text-ibook-brown-900 placeholder-ibook-brown-300 bg-white focus:outline-none focus:ring-2 focus:ring-ibook-brown-400 focus:border-ibook-brown-400 transition-colors"
      />
      <p v-if="errors.phone" class="mt-1.5 text-sm text-red-600">{{ errors.phone }}</p>
    </div>

    <!-- General error -->
    <div
      v-if="errors.general"
      class="mb-5 px-4 py-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700"
    >
      {{ errors.general }}
    </div>

    <!-- Submit -->
    <button
      type="submit"
      :disabled="loading"
      class="w-full py-3 px-6 bg-ibook-brown-700 hover:bg-ibook-brown-600 text-white font-semibold rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-ibook-brown-400 focus:ring-offset-2 disabled:opacity-60 disabled:cursor-not-allowed cursor-pointer"
    >
      <span v-if="loading">Creating account…</span>
      <span v-else>Create Account</span>
    </button>
  </form>
</template>
