// frontend/src/components/auth/LoginForm.tsx
'use client'

import { useState } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { useRouter } from 'next/navigation'
import Link from 'next/link'
import Cookies from 'js-cookie'
import { api } from '@/lib/axios'
import { useAuth } from '@/hooks/useAuth'
import {
  Form,
  FormField,
  FormItem,
  FormLabel,
  FormControl,
  FormMessage,
} from '@/components/ui/form'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'

const loginSchema = z.object({
  email: z.string().email('Please enter a valid email address'),
  password: z.string().min(1, 'Password is required'),
})

type LoginFormValues = z.infer<typeof loginSchema>

interface LoginResponse {
  access: string
  user: {
    id: number
    email: string
    role: 'CUSTOMER' | 'BARBER' | 'SHOP_OWNER'
    full_name: string
  }
}

export function LoginForm() {
  const router = useRouter()
  const { setAuth } = useAuth()
  const [serverError, setServerError] = useState<string | null>(null)

  const form = useForm<LoginFormValues>({
    resolver: zodResolver(loginSchema),
    defaultValues: { email: '', password: '' },
  })

  const onSubmit = async (values: LoginFormValues) => {
    setServerError(null)
    try {
      const { data } = await api.post<LoginResponse>('/api/auth/login/', {
        email: values.email,
        password: values.password,
      })

      // Store in Zustand
      setAuth(
        {
          id: data.user.id,
          email: data.user.email,
          role: data.user.role,
          fullName: data.user.full_name,
        },
        data.access
      )

      // Set non-httpOnly cookie so middleware.ts can read it
      // Expires in 15 minutes (1/96 of a day)
      Cookies.set('access_token', data.access, { expires: 1 / 96, sameSite: 'lax' })

      // Role-based redirect
      if (data.user.role === 'CUSTOMER') {
        router.push('/customer/explore')
      } else if (data.user.role === 'BARBER') {
        router.push('/barber/dashboard')
      } else if (data.user.role === 'SHOP_OWNER') {
        router.push('/owner/overview')
      }
    } catch (err: unknown) {
      const error = err as { response?: { data?: { detail?: string; non_field_errors?: string[] } } }
      const detail =
        error?.response?.data?.detail ||
        error?.response?.data?.non_field_errors?.[0] ||
        'Invalid email or password. Please try again.'
      setServerError(detail)
    }
  }

  return (
    <div className="space-y-8">
      <div>
        <h2 className="text-3xl font-bold text-ibook-brown-900">Welcome back</h2>
        <p className="mt-2 text-ibook-brown-500">Sign in to your IBook account</p>
      </div>

      <Form {...form}>
        <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-5">
          <FormField
            control={form.control}
            name="email"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="text-ibook-brown-700 font-medium">Email</FormLabel>
                <FormControl>
                  <Input
                    type="email"
                    placeholder="you@example.com"
                    autoComplete="email"
                    className="bg-white border-ibook-brown-100 focus:border-ibook-gold-400"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel className="text-ibook-brown-700 font-medium">Password</FormLabel>
                <FormControl>
                  <Input
                    type="password"
                    placeholder="••••••••"
                    autoComplete="current-password"
                    className="bg-white border-ibook-brown-100 focus:border-ibook-gold-400"
                    {...field}
                  />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          {serverError && (
            <div className="rounded-lg border border-destructive/50 bg-destructive/10 px-4 py-3 text-sm text-destructive">
              {serverError}
            </div>
          )}

          <Button
            type="submit"
            disabled={form.formState.isSubmitting}
            className="w-full bg-ibook-brown-700 hover:bg-ibook-brown-900 text-white font-semibold py-2.5 rounded-xl h-auto"
          >
            {form.formState.isSubmitting ? 'Signing in…' : 'Sign in'}
          </Button>
        </form>
      </Form>

      <p className="text-center text-sm text-ibook-brown-500">
        Don&apos;t have an account?{' '}
        <Link
          href="/register/customer"
          className="font-medium text-ibook-brown-700 underline underline-offset-4"
        >
          Sign up
        </Link>
      </p>
    </div>
  )
}

// frontend/src/components/auth/LoginForm.vue
<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter } from 'vue-router'
import api from '@/lib/axios'
import { useAuthStore } from '@/stores/auth'
import type { UserRole } from '@/stores/auth'
import { roleDashboard } from '@/router'
import Cookies from 'js-cookie'

const router = useRouter()
const auth = useAuthStore()

const form = reactive({
  email: '',
  password: '',
})

const errors = reactive({
  email: '',
  password: '',
  general: '',
})

const loading = ref(false)

function validateEmail(email: string) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)
}

function validate() {
  errors.email = ''
  errors.password = ''
  errors.general = ''
  let valid = true

  if (!form.email) {
    errors.email = 'Email is required.'
    valid = false
  } else if (!validateEmail(form.email)) {
    errors.email = 'Please enter a valid email address.'
    valid = false
  }

  if (!form.password) {
    errors.password = 'Password is required.'
    valid = false
  }

  return valid
}

async function submit() {
  if (!validate()) return
  loading.value = true
  errors.general = ''

  try {
    const res = await api.post<{
      access: string
      user: { id: number; email: string; role: UserRole; full_name: string }
    }>('/api/auth/login/', {
      email: form.email,
      password: form.password,
    })

    const { access, user } = res.data

    auth.setAuth({
      accessToken: access,
      user: {
        id: user.id,
        email: user.email,
        role: user.role,
        fullName: user.full_name,
      },
    })

    Cookies.set('access_token', access, { sameSite: 'strict' })

    const returnUrl = (router.currentRoute.value.query.returnUrl as string) || ''
    const destination = returnUrl || roleDashboard(user.role)
    router.push(destination)
  } catch (err: unknown) {
    const axiosErr = err as { response?: { data?: { detail?: string; non_field_errors?: string[] } } }
    const detail = axiosErr.response?.data?.detail
    const nonField = axiosErr.response?.data?.non_field_errors?.[0]
    errors.general = detail || nonField || 'Invalid email or password. Please try again.'
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <form @submit.prevent="submit" novalidate>
    <!-- Email -->
    <div class="mb-5">
      <label for="email" class="block text-sm font-semibold text-ibook-brown-700 mb-1.5">
        Email
      </label>
      <input
        id="email"
        v-model="form.email"
        type="email"
        autocomplete="email"
        placeholder="you@example.com"
        class="w-full px-4 py-3 rounded-lg border text-ibook-brown-900 placeholder-ibook-brown-300 bg-white focus:outline-none focus:ring-2 transition-colors"
        :class="
          errors.email
            ? 'border-red-400 focus:ring-red-300'
            : 'border-ibook-brown-200 focus:ring-ibook-brown-400 focus:border-ibook-brown-400'
        "
      />
      <p v-if="errors.email" class="mt-1.5 text-sm text-red-600">{{ errors.email }}</p>
    </div>

    <!-- Password -->
    <div class="mb-6">
      <label for="password" class="block text-sm font-semibold text-ibook-brown-700 mb-1.5">
        Password
      </label>
      <input
        id="password"
        v-model="form.password"
        type="password"
        autocomplete="current-password"
        placeholder="••••••••"
        class="w-full px-4 py-3 rounded-lg border text-ibook-brown-900 placeholder-ibook-brown-300 bg-white focus:outline-none focus:ring-2 transition-colors"
        :class="
          errors.password
            ? 'border-red-400 focus:ring-red-300'
            : 'border-ibook-brown-200 focus:ring-ibook-brown-400 focus:border-ibook-brown-400'
        "
      />
      <p v-if="errors.password" class="mt-1.5 text-sm text-red-600">{{ errors.password }}</p>
    </div>

    <!-- General error -->
    <div
      v-if="errors.general"
      class="mb-5 px-4 py-3 bg-red-50 border border-red-200 rounded-lg text-sm text-red-700"
    >
      {{ errors.general }}
    </div>

    <!-- Submit -->
    <button
      type="submit"
      :disabled="loading"
      class="w-full py-3 px-6 bg-ibook-brown-700 hover:bg-ibook-brown-600 text-white font-semibold rounded-lg transition-colors focus:outline-none focus:ring-2 focus:ring-ibook-brown-400 focus:ring-offset-2 disabled:opacity-60 disabled:cursor-not-allowed cursor-pointer"
    >
      <span v-if="loading">Signing in…</span>
      <span v-else>Sign In</span>
    </button>
  </form>
</template>
